<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="wheelchair">

  <xacro:property name="wheel_radius" value="0.15"/>
  <xacro:property name="wheel_separation" value="0.55"/>
  <xacro:property name="base_height" value="0.15"/>
  <xacro:property name="base_width" value="0.6"/>
  <xacro:property name="base_length" value="0.8"/>

  <!-- Base link -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="grey">
        <color rgba="0.4 0.4 0.4 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="30"/>
      <inertia ixx="1" ixy="0.0" ixz="0.0"
               iyy="1" iyz="0.0"
               izz="1"/>
    </inertial>
  </link>

  <!-- Left wheel -->
  <link name="left_wheel">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="0.05"/>
      </geometry>
      <material name="black">
        <color rgba="0 0 0 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${wheel_radius}" length="0.05"/>
      </geometry>
    </collision>
    <inertial><mass value="2"/></inertial>
  </link>

  <!-- Right wheel -->
  <link name="right_wheel">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="0.05"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${wheel_radius}" length="0.05"/>
      </geometry>
    </collision>
    <inertial><mass value="2"/></inertial>
  </link>

  <!-- Wheel joints -->
  <joint name="left_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="left_wheel"/>
    <origin xyz="0 ${wheel_separation/2} 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <joint name="right_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="right_wheel"/>
    <origin xyz="0 -${wheel_separation/2} 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <gazebo>
    <plugin name="diff_drive" filename="libgazebo_ros_diff_drive.so">
      <ros>
        <namespace>/</namespace>
        <remapping>cmd_vel:=/cmd_vel</remapping>
      </ros>
      <robotBaseFrame>base_link</robotBaseFrame>
      <leftJoint>left_wheel_joint</leftJoint>
      <rightJoint>right_wheel_joint</rightJoint>
      <wheelSeparation>${wheel_separation}</wheelSeparation>
      <wheelDiameter>${2 * wheel_radius}</wheelDiameter>
      <torque>20</torque>
      <maxWheelSpeed>10</maxWheelSpeed>
    </plugin>
  </gazebo>

</robot>
